window.ECOSYSTEM_DATA = {
  groups: [
    { id: 'interface', label: 'INTERFACE / CONTROL CENTER', x: -16.0, y: 5.5, color: '#00ffa0' },
    { id: 'pipeline', label: 'PIPELINE', x: -8.0, y: 9.5, color: '#00ccff' },
    { id: 'engines', label: 'ENGINES', x: 7.9, y: 5.6, color: '#ff8844' },
    { id: 'knowledge', label: 'KNOWLEDGE', x: 0, y: -8.0, color: '#ffaa00' },
    { id: 'modelsgrp', label: 'MODELS', x: 13.2, y: 1.4, color: '#ff66aa' },
    { id: 'ocmodels', label: 'OC MODELS', x: 2.9, y: 1.1, color: '#00ffa0' }
  ],
  nodes: [
    { id: 'onedrive',  y: -9.5, x: -4.0, z: -0.3, group: 'knowledge',
      label: 'OneDrive Docs',
      detail: 'dev-context.md · session logs',
      badge: 'Sync', env: 'WIN' },
    { id: 'config',    y: -9.5, x: 0, z: -0.5, group: 'knowledge',
      label: 'Config Store',
      detail: 'opencode.jsonc · instructions/',
      badge: 'Config', env: 'WSL' },
    { id: 'sessionlog', y: -9.5, x: 4.0, z: -0.3, group: 'knowledge',
      label: 'Session Log',
      detail: 'log-session · timestamped history',
      badge: 'Log', env: 'WSL' },
    { id: 'browser',   y: 2.0, x: -16.0, z: -1.0, group: 'interface',
      label: 'Browser',
      detail: 'Vox Orby 3D · SSE events',
      badge: 'Frontend', env: 'WIN' },
    { id: 'zed',      y: 4.0, x: -16.0, z: -1.5, group: 'interface',
      label: 'Zed',
      detail: 'Rust · GPU accelerated · Helium',
      badge: 'Editor', env: 'WIN' },
    { id: 'terminal',  y: 0, x: -16.0, z: -1.0, group: 'interface',
      label: 'Terminal',
      detail: 'PowerShell · WSL bash',
      badge: 'Shell', env: 'BOTH' },
    { id: 'tmux',      y: -4.0, x: -16.0, z: -0.5, group: 'interface',
      label: 'tmux',
      detail: 'terminal multiplexer · persistent sessions',
      badge: 'Shell', env: 'WSL' },
    { id: 'whisper',   y: 8.0, x: -8.0, z: 0.3, group: 'pipeline',
      label: 'whisper.cpp',
      detail: 'STT engine · port 8760',
      badge: 'Inference', env: 'WSL' },
    { id: 'fastapi',   y: 4.0, x: -8.0, z: 0, group: 'pipeline',
      label: 'FastAPI Server',
      detail: 'port 8080 · SSE · /api/reason',
      badge: 'Bridge', env: 'WSL' },
    { id: 'opencode',  y: 0, x: -8.0, z: 0, group: 'pipeline',
      label: 'OpenCode',
      detail: '3 plugins · Ollama models · shared session',
      badge: 'Agent', env: 'WSL' },
    { id: 'dsv4free',  y: -0.4, x: 1.9, z: 0.5, group: 'ocmodels',
      label: 'DeepSeek V4 Free',
      detail: '1M ctx · 284B MoE · flash free',
      badge: 'Free', env: 'CLOUD' },
    { id: 'bigpickle',  y: -1.9, x: 1.9, z: 0.4, group: 'ocmodels',
      label: 'Big Pickle',
      detail: '200K ctx · stealth model · free',
      badge: 'Free', env: 'CLOUD' },
    { id: 'mimifree',   y: -3.4, x: 1.9, z: 0.3, group: 'ocmodels',
      label: 'MiMi-V2.5 Free',
      detail: 'MiniMax · free tier',
      badge: 'Free', env: 'CLOUD' },
    { id: 'northmini',  y: -4.9, x: 1.9, z: 0.3, group: 'ocmodels',
      label: 'North Mini Code',
      detail: 'Cohere · free code model',
      badge: 'Free', env: 'CLOUD' },
    { id: 'nemotron',   y: -6.4, x: 1.9, z: 0.4, group: 'ocmodels',
      label: 'Nemotron 3 Ultra',
      detail: 'Nvidia · free ultra model',
      badge: 'Free', env: 'CLOUD' },
    { id: 'fuchetts',  y: -4.0, x: -8.0, z: -0.3, group: 'pipeline',
      label: 'fuche-tts',
      detail: 'GPU BF16 · Audio FX',
      badge: 'TTS Engine', env: 'WSL' },
    { id: 'heartbeat', y: 8.0, x: 0, z: 0,
      label: 'Heartbeat',
      detail: 'cron 1min · stretch 30min · TTS alive',
      badge: 'Pro', env: 'WSL' },
    { id: 'kitten-rs', y: -5.0, x: -8.0, z: 0.5,
      label: 'kitten-rs',
      detail: 'KittenML ONNX · port 8750',
      badge: 'Engine', env: 'WSL' },
    { id: 'ollama',    y: 5.5, x: 7.9, z: 0.2, group: 'engines',
      label: 'Ollama',
      detail: '10 models · qwen3-coder · gemma4 · ornith · more',
      badge: 'Backend', env: 'WSL' },
    { id: 'qwen3coder', y: 3.5, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'Qwen3 Coder',
      detail: '18B · latest · 480b-cloud',
      badge: 'LLM', env: 'WIN' },
    { id: 'gemma4',     y: 2.0, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'Gemma 4',
      detail: '31B-cloud · e2b:q4',
      badge: 'LLM', env: 'WIN' },
    { id: 'qwen35cc',   y: 0.5, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'Qwen3.5 Coder',
      detail: '4B · claude-coder variant',
      badge: 'LLM', env: 'WIN' },
    { id: 'ornith',    y: -1.0, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'Ornith-32k',
      detail: '9B · 32K RoPE · custom Modelfile',
      badge: 'LLM', env: 'WSL' },
    { id: 'deepseek',  y: -2.5, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'DeepSeek MCP',
      detail: 'proxy bridge · 3 plugins',
      badge: 'MCP', env: 'BOTH' },
    { id: 'nanbeige',  y: -4.0, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'Nanbeige-16k',
      detail: '3B · 16K ctx · Q4_K_M',
      badge: 'LLM', env: 'WSL' },
    { id: 'llama32',    y: -5.5, x: 13.2, z: 0, group: 'modelsgrp',
      label: 'Llama 3.2',
      detail: '3B · latest',
      badge: 'LLM', env: 'WIN' },
    { id: 'superharness', y: -1.2, x: -13.5, z: 0, group: 'interface',
      label: 'superharness',
      detail: 'v0.3.3 · plugin · uses tmux',
      badge: 'Plugin', env: 'WSL' },
    { id: 'vecsearch', y: 2.0, x: -4.0, z: 0, group: 'pipeline',
      label: 'Vector Search',
      detail: '208 chunks · cosine sim · 376 KB index',
      badge: 'Semantic', env: 'WSL' }
  ],
  connections: [
    { from: 0, to: 1 },  { from: 1, to: 2 },
    { from: 5, to: 6 },  { from: 6, to: 26 },
    { from: 7, to: 8 },  { from: 8, to: 9 },  { from: 9, to: 15 }
  ],
  crossConnections: [
    { from: 3, to: 8 },
    { from: 'knowledge', to: 9 },
    { from: 9, to: 18 },
    { from: 18, to: 'modelsgrp' },
    { from: 15, to: 17 },
    { from: 16, to: 9 },
    { from: 9, to: 26 },
    { from: 6, to: 5 },
    { from: 9, to: 'ocmodels' },
    { from: 9, to: 27 },
    { from: 27, to: 'knowledge' }
  ]
};
