window.ECOSYSTEM_DATA = {
  groups: [
    { id: 'interface', label: 'INTERFACE', x: -16.0, y: 5.5, color: '#00ffa0' },
    { id: 'pipeline', label: 'PIPELINE', x: -8.0, y: 5.5, color: '#00ccff' },

    { id: 'engines', label: 'ENGINES', x: 8.0, y: 5.5, color: '#ff8844' },
    { id: 'knowledge', label: 'KNOWLEDGE', x: 0, y: -7.0, color: '#ffaa00' },
    { id: 'modelsgrp', label: 'MODELS', x: 16.0, y: -0.5, color: '#ff66aa' }
  ],
  nodes: [
    { id: 'onedrive',  y: -9.5, x: -4.0, z: -0.3, group: 'knowledge',
      label: 'OneDrive Docs',
      detail: 'dev-context.md · session logs',
      badge: 'Sync' },
    { id: 'config',    y: -9.5, x: 0, z: -0.5, group: 'knowledge',
      label: 'Config Store',
      detail: 'opencode.jsonc · instructions/',
      badge: 'Config' },
    { id: 'sessionlog', y: -9.5, x: 4.0, z: -0.3, group: 'knowledge',
      label: 'Session Log',
      detail: 'log-session · timestamped history',
      badge: 'Log' },
    { id: 'browser',   y: 0,   x: -16.0, z: -1.0, group: 'interface',
      label: 'Browser',
      detail: 'Vox Orby 3D · SSE events',
      badge: 'Frontend' },
    { id: 'whisper',   y: 4.5, x: -8.0, z: 0.3, group: 'pipeline',
      label: 'whisper.cpp',
      detail: 'STT engine · port 8760',
      badge: 'Inference' },
    { id: 'fastapi',   y: 1.5, x: -8.0, z: 0, group: 'pipeline',
      label: 'FastAPI Server',
      detail: 'port 8080 · SSE · /api/reason',
      badge: 'Bridge' },
    { id: 'opencode',  y: -1.5, x: -8.0, z: 0, group: 'pipeline',
      label: 'OpenCode',
      detail: '3 plugins · Ollama models · shared session',
      badge: 'Agent' },
    { id: 'fuchetts',  y: -4.5, x: -8.0, z: -0.3, group: 'pipeline',
      label: 'fuche-tts',
      detail: 'GPU BF16 · Audio FX',
      badge: 'TTS Engine' },
    { id: 'heartbeat', y: 2.0, x: -8.0, z: 1.5,
      label: '❤️ Heartbeat',
      detail: 'cron 1min · stretch 30min · TTS alive',
      badge: 'Pro' },
    { id: 'kitten-rs', y: -6.5, x: -8.0, z: 0.5,
      label: 'kitten-rs',
      detail: 'KittenML ONNX · port 8750',
      badge: 'Engine' },
    { id: 'ollama',    y: 2.0, x: 8.0, z: 0.2, group: 'engines',
      label: 'Ollama',
      detail: 'LLM server · GGUF runner',
      badge: 'Backend' },
    { id: 'ornith',    y: 0.0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'Ornith-32k',
      detail: '9B · 32K RoPE · custom Modelfile',
      badge: 'LLM' },
    { id: 'deepseek',  y: -2.0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'DeepSeek MCP',
      detail: 'proxy bridge · 3 plugins',
      badge: 'MCP' },
    { id: 'nanbeige',  y: -4.0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'Nanbeige-16k',
      detail: '3B · 16K ctx · Q4_K_M',
      badge: 'LLM' },
    { id: 'zen',       y: -6.0, x: 16.0, z: 0.5, group: 'modelsgrp',
      label: 'Zen Models',
      detail: 'Qwen3 · Kokoro · whisper.cpp',
      badge: 'Multi' }
  ],
  connections: [
    { from: 0, to: 1 },  { from: 1, to: 2 },
    { from: 4, to: 5 },  { from: 5, to: 6 },  { from: 6, to: 7 }
  ],
  crossConnections: [
    { from: 3, to: 5 },
    { from: 'knowledge', to: 6 },
    { from: 6, to: 10 },
    { from: 7, to: 9 },
    { from: 6, to: 8 }
  ]
};
