window.ECOSYSTEM_DATA = {
  groups: [
    { id: 'interface', label: 'INTERFACE', x: -16.0, y: 5.5, color: '#00ffa0' },
    { id: 'pipeline', label: 'PIPELINE', x: -8.0, y: 5.5, color: '#00ccff' },

    { id: 'engines', label: 'ENGINES', x: 8.0, y: 5.5, color: '#ff8844' },
    { id: 'knowledge', label: 'KNOWLEDGE', x: 0, y: -7.0, color: '#ffaa00' },
    { id: 'modelsgrp', label: 'MODELS', x: 16.0, y: -0.5, color: '#ff66aa' }
  ],
  nodes: [
    { id: 'onedrive',  y: -9.5, x: -4.0, z: -0.3, group: 'knowledge',
      label: 'OneDrive Docs',
      detail: 'dev-context.md · session logs',
      badge: 'Sync', env: 'WIN' },
    { id: 'config',    y: -9.5, x: 0, z: -0.5, group: 'knowledge',
      label: 'Config Store',
      detail: 'opencode.jsonc · instructions/',
      badge: 'Config', env: 'WSL' },
    { id: 'sessionlog', y: -9.5, x: 4.0, z: -0.3, group: 'knowledge',
      label: 'Session Log',
      detail: 'log-session · timestamped history',
      badge: 'Log', env: 'WSL' },
    { id: 'browser',   y: 2.0, x: -16.0, z: -1.0, group: 'interface',
      label: 'Browser',
      detail: 'Vox Orby 3D · SSE events',
      badge: 'Frontend', env: 'WIN' },
    { id: 'zed',      y: 4.0, x: -16.0, z: -1.5, group: 'interface',
      label: 'Zed',
      detail: 'Rust · GPU accelerated · Helium',
      badge: 'Editor', env: 'WIN' },
    { id: 'terminal',  y: 0, x: -16.0, z: -1.0, group: 'interface',
      label: 'Terminal',
      detail: 'PowerShell · WSL bash',
      badge: 'Shell', env: 'BOTH' },
    { id: 'tmux',      y: -4.0, x: -16.0, z: -0.5, group: 'interface',
      label: 'tmux',
      detail: 'terminal multiplexer · persistent sessions',
      badge: 'Shell', env: 'WSL' },
    { id: 'whisper',   y: 4.0, x: -8.0, z: 0.3, group: 'pipeline',
      label: 'whisper.cpp',
      detail: 'STT engine · port 8760',
      badge: 'Inference', env: 'WSL' },
    { id: 'fastapi',   y: 2.0, x: -8.0, z: 0, group: 'pipeline',
      label: 'FastAPI Server',
      detail: 'port 8080 · SSE · /api/reason',
      badge: 'Bridge', env: 'WSL' },
    { id: 'opencode',  y: 0, x: -8.0, z: 0, group: 'pipeline',
      label: 'OpenCode',
      detail: '3 plugins · Ollama models · shared session',
      badge: 'Agent', env: 'WSL' },
    { id: 'fuchetts',  y: -2.0, x: -8.0, z: -0.3, group: 'pipeline',
      label: 'fuche-tts',
      detail: 'GPU BF16 · Audio FX',
      badge: 'TTS Engine', env: 'WSL' },
    { id: 'heartbeat', y: 8.0, x: 0, z: 0,
      label: 'Heartbeat',
      detail: 'cron 1min · stretch 30min · TTS alive',
      badge: 'Pro', env: 'WSL' },
    { id: 'kitten-rs', y: -4.0, x: -8.0, z: 0.5,
      label: 'kitten-rs',
      detail: 'KittenML ONNX · port 8750',
      badge: 'Engine', env: 'WSL' },
    { id: 'ollama',    y: 2.0, x: 8.0, z: 0.2, group: 'engines',
      label: 'Ollama',
      detail: 'Ornith-32k · Nanbeige-16k · DeepSeek · Zen',
      badge: 'Backend', env: 'WSL' },
    { id: 'ornith',    y: 0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'Ornith-32k',
      detail: '9B · 32K RoPE · custom Modelfile',
      badge: 'LLM', env: 'WSL' },
    { id: 'deepseek',  y: -2.0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'DeepSeek MCP',
      detail: 'proxy bridge · 3 plugins',
      badge: 'MCP', env: 'BOTH' },
    { id: 'nanbeige',  y: -4.0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'Nanbeige-16k',
      detail: '3B · 16K ctx · Q4_K_M',
      badge: 'LLM', env: 'WSL' },
    { id: 'zen',       y: -6.0, x: 16.0, z: 0.5, group: 'modelsgrp',
      label: 'Zen Models',
      detail: 'Qwen3 · Kokoro · whisper.cpp',
      badge: 'Multi', env: 'WSL' },
    { id: 'freemodels', y: -8.0, x: 16.0, z: 0, group: 'modelsgrp',
      label: 'Free Models',
      detail: 'open · GGUF · community',
      badge: 'Free', env: 'WSL' },
    { id: 'superharness', y: -2.0, x: -16.0, z: 0, group: 'interface',
      label: 'superharness',
      detail: 'v0.3.3 · plugin · uses tmux',
      badge: 'Plugin', env: 'WSL' }
  ],
  connections: [
    { from: 0, to: 1 },  { from: 1, to: 2 },
    { from: 7, to: 8 },  { from: 8, to: 9 },  { from: 9, to: 10 }
  ],
  crossConnections: [
    { from: 3, to: 8 },
    { from: 'knowledge', to: 9 },
    { from: 9, to: 13 },
    { from: 13, to: 'modelsgrp' },
    { from: 10, to: 12 },
    { from: 11, to: 9 },
    { from: 9, to: 18 },
    { from: 6, to: 5 }
  ]
};
